//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coft_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodImg
    {
        public int imgFId { get; set; }
        public string imgFLink { get; set; }
        public int foodId { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
